trainingInput:
  ## BASIC_GPU uses single NVIDIA Tesla K80 GPU.
  scaleTier: BASIC_GPU
  ## Custom scaleTier needed for using > 1 GPU machines.
  # scaleTier: CUSTOM
  # masterType: complex_model_m_gpu
  # workerType: complex_model_m_gpu
  # parameterServerType: large_model
  # workerCount: 9
  # parameterServerCount: 3
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: auc
    maxTrials: 100
    maxParallelTrials: 10
    enableTrialEarlyStopping: TRUE
    params:
      - parameterName: embedding_size
        type: INTEGER
        minValue: 50
        maxValue: 200
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: num_filters
        type: INTEGER
        minValue: 10
        maxValue: 200
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: dropout_keep_prob
        type: DOUBLE
        minValue: 0.5
        maxValue: 1
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: learning_rate
        type: DOUBLE
        minValue: 0.000001
        maxValue: 0.1
        scaleType: UNIT_LOG_SCALE